### ISSUE TITLE
upgrade to v0.7.4 of app registry 

### ISSUE THREAD

**Issue by jeff-knurek** [samsung-cnct/docker-helm-registry-agent#12]
https://github.com/app-registry/appr/issues/67 is fixed in v0.7.4. 
If we continue using your docker image, we need a new version released & tagged.

**Comment by venezia** [comment]
@jeff-knurek there are now two tagged releases you can use

quay.io/samsung_cnct/helm-registry-agent:v0.7.4-helm_2.6
* has v0.7.4 of appr
* has helm v2.6.1 installed

quay.io/samsung_cnct/helm-registry-agent:v0.7.4-helm_2.5
* has v0.7.4 of appr
* has helm v2.5.1 installed

There's also less-exact tags
* quay.io/samsung_cnct/helm-registry-agent:helm_2.6
* quay.io/samsung_cnct/helm-registry-agent:helm_2.5

These will always have the latest appr with the latest bugfix release of a helm minor release.

This is necessary as helm minor releases are incompatible with each other.  Eventually we will have a helm_2.7, helm_2.8, etc.

Thanks for the ticket!
